import math
import random
from enum import Enum

from models.landmark import Landmark
from models.problem import Problem
from models.tour import Tour
from .solver import Solver
from .greedy_solver import GreedySolver


class AcceptanceFunction(Enum):
    BOLTZMANN = 1
    CAUCHY = 2

class DecayFunction(Enum):
    EXPONENTIAL = 1
    LINEAR = 2

class SimulatedAnnealingSolver(Solver):
    def __init__(
        self,
        problem: Problem,
        acceptance_criterion: AcceptanceFunction = AcceptanceFunction.BOLTZMANN,
        initial_temperature: float = 10,
        cooling_rate: float = 0.95,
        reheating_rate: float = 0,
        decay_function: DecayFunction = DecayFunction.EXPONENTIAL,
        max_iterations: int = 10000,
    ) -> None:
        """
        Simulated Annealing solver for the Orienteering Problem.

        Args:
            problem (Problem): The problem instance to solve.
            acceptance_criterion (AcceptanceFunction, optional): The acceptance criterion to use (BOLTZMANN or CAUCHY). Defaults to AcceptanceFunction.BOLTZMANN.
            initial_temperature (float, optional): The initial temperature for the annealing process. Defaults to 10.
            cooling_rate (float, optional): The rate at which the temperature decreases. Defaults to 0.95.
            reheating_rate (float, optional): The rate at which the temperature increases when the temperature stops decreasing (set to 0 for no reheating, to 1 for multi-start restart strategy). Defaults to 0.
            decay_function (DecayFunction, optional): The decay function to use for the temperature decrease. Defaults to DecayFunction.EXPONENTIAL.
            max_iterations (int, optional): The maximum number of iterations to perform. Defaults to 10000.
        """

        if initial_temperature <= 0:
            raise ValueError("Initial temperature must be positive")
        if cooling_rate <= 0 or cooling_rate >= 1:
            raise ValueError("Cooling rate must be between 0 and 1")
        if reheating_rate < 0 or reheating_rate > 1:
            raise ValueError("Reheating rate must be between 0 and 1")
        if max_iterations <= 0:
            raise ValueError("Max iterations must be positive")

        super().__init__(problem)
        self.acceptance_criterion = acceptance_criterion
        self.initial_temperature = initial_temperature
        self.cooling_rate = cooling_rate
        self.reheating_rate = reheating_rate
        self.decay_function = decay_function
        self.max_iterations = max_iterations

    def _acceptance_probability(self, delta: float, temperature: float) -> float:
        """
        Calculate the acceptance probability based on the chosen acceptance criterion.

        Args:
            delta (float): The change in the objective function value (new_value - current_value).
            temperature (float): The current temperature in the annealing process.
        Returns:
            float: The acceptance probability.
        """

        if delta > 0:
            return 1.0

        if temperature <= 0:
            return 0.0 
        
        if self.acceptance_criterion == AcceptanceFunction.BOLTZMANN:
            return min(1, math.exp(delta / temperature))
        elif self.acceptance_criterion == AcceptanceFunction.CAUCHY:
            return min(1, 1 / (1 + delta**2 / temperature))
        else:
            raise ValueError("Invalid acceptance criterion")
        
    
    def _swap_operator(self, tour: Tour) -> Tour:
        """
        Randomly swap two landmarks in the tour to generate a new candidate solution.

        Args:
            tour (Tour): The current tour to modify.
        Returns:
            Tour: A new tour generated by swapping two landmarks.
        """

        if len(tour.visited_landmarks) < 2:
            return tour.copy()  # No swap possible, return a copy of the original tour

        i, j = random.sample(range(len(tour.visited_landmarks)), 2)
        tour = tour.copy()
        tour.swap_by_index(i, j)
        return tour
    
    def _insert_operator(self, tour: Tour) -> Tour:
        """
        Randomly insert a new landmark into the tour to generate a new candidate solution.

        Args:
            tour (Tour): The current tour to modify.
        Returns:
            Tour: A new tour generated by swapping two landmarks.
        """
        landmarks = self.problem.feasible_candidates(tour)
        if not landmarks:
            return tour
        new_landmark = random.choice(list(landmarks))
        position = random.randint(0, len(tour.visited_landmarks))
        tour = tour.copy()
        tour.add_landmark(new_landmark, position)
        tour._invalidate_cache()
        return tour
    
    def _remove_operator(self, tour: Tour) -> Tour:
        """
        Randomly remove a landmark from the tour to generate a new candidate solution.

        Args:
            tour (Tour): The current tour to modify.
        Returns:
            Tour: A new tour generated by swapping two landmarks.
        """
        if not tour.visited_landmarks:
            return tour
        position = random.randint(0, len(tour.visited_landmarks) - 1)
        tour = tour.copy()
        tour.remove_landmark(tour.visited_landmarks[position])
        tour._invalidate_cache()
        return tour
    
    def _invert_operator(self, tour: Tour) -> Tour:
        """
        Randomly invert a subsequence of landmarks in the tour to generate a new candidate solution.

        Args:
            tour (Tour): The current tour to modify.
        Returns:
            Tour: A new tour generated by swapping two landmarks.
        """
        if len(tour.visited_landmarks) < 2:
            return tour
        i, j = sorted(random.sample(range(len(tour.visited_landmarks)), 2))
        tour = tour.copy()
        tour.visited_landmarks[i:j+1] = reversed(tour.visited_landmarks[i:j+1])
        tour._invalidate_cache()
        return tour
        

    OPERATORS = [_swap_operator, _insert_operator, _remove_operator, _invert_operator]

    def solve(self) -> Tour:
        """
        Solve the problem using the Simulated Annealing algorithm.
        Returns:
            Tour: The best tour found during the annealing process.
        """

        if not self.OPERATORS:
            raise ValueError("No operators defined for Simulated Annealing")

        try:
            state = GreedySolver(self.problem).solve()
        except Exception as e:
            raise RuntimeError("Failed to generate initial solution with GreedySolver") from e

        if not state.is_valid():
            raise RuntimeError("Initial solution is invalid")

        start_temperature = self.initial_temperature
        temperature = start_temperature

        best_state = state

        for _ in range(self.max_iterations):

            
            next_state = self.OPERATORS[random.randint(0, len(self.OPERATORS) - 1)](self, state)
           
            if not next_state.is_valid():
                continue

            delta_E = next_state.total_score() - state.total_score() 

            if self._acceptance_probability(delta_E, temperature) > random.uniform(0, 1):
                state = next_state

                if state.total_score() > best_state.total_score():
                    best_state = state

            if self.decay_function == DecayFunction.EXPONENTIAL:
                temperature *= self.cooling_rate
            elif self.decay_function == DecayFunction.LINEAR:
                temperature = max(temperature - self.cooling_rate, 0)

            if temperature < 1e-8:
                start_temperature *= self.reheating_rate
                if start_temperature > 1e-8:
                    temperature = start_temperature
                else:
                    break
            

        return best_state
